### ISSUE TITLE
File sending not working

### ISSUE THREAD

**Issue by fidderr** [nextcloud/talk-desktop#473]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Click on the paperclip next to the `Write a message` box
3. Click `Upload from device`
4. Choose a file
5. Click Send

### Expected behaviour
The file should be send to the conversation.

### Actual behaviour
Nothing happens. the send button does nothing.

## Desktop client

----------------------------System report----------------------------
Nextcloud Talk Desktop version 0.19.0
- Built with Nextcloud Talk version 18.0.0

Connected to:
- Server address: https://xxx.xxx.xx
- Nextcloud Server version 27.1.5
- Nextcloud Talk version 17.1.4

OS: Windows_NT 10.0.19045 (Windows 10 Pro)
----------------------------System report----------------------------

Javascript console log when clicking the button:

index.js:2 TypeError: Cannot destructure property 'caption' of 'object null' as it is null.
    at o.handleUpload (index.js:2:408796)
    at click (index.js:2:407254)
    at on (index.js:2:686486)
    at o.n (index.js:2:679770)
    at on (index.js:2:686486)
    at e.$emit (index.js:2:707911)
    at click (index.js:2:1181051)
    at on (index.js:2:686486)
    at HTMLButtonElement.n (index.js:2:679770)
    at Pa.s._wrapper (index.js:2:719577)

**Comment by ShGKme** [comment]
@Antreesy Could you have a look?

**Comment by Antreesy** [comment]
Regression from here: https://github.com/nextcloud/spreed/commit/fe630afa60c114297de4a423d94831b6b3ebbcc5

**Comment by nickvergessen** [comment]
> Built with Nextcloud Talk version 18.0.0-rc.2

Latest version of Desktop is:
```
Nextcloud Talk Desktop version 0.19.0
- Built with Nextcloud Talk version 18.0.0
```

but latest Talk is 18.0.1, so it's lacking behind. Can we do 0.19.1 or 0.20.0 :) 

Looking at https://github.com/nextcloud/spreed/issues?q=is%3Aclosed+milestone%3A%22%F0%9F%92%99+Next+Patch+%2828%29%22 we could to a 18.0.2 before as well, but that was only planned for 25th January.
