### ISSUE TITLE
Package path `./dist/Composables/useIsMobile.js` is not exported from package `@nextcloud/vue`

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-desktop#487]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Try to build main with Talk's main

### Expected behaviour
🚀 

### Actual behaviour
```
An unhandled rejection has occurred inside Forge:
Error: Compilation errors in the preload: group_0:
  asset authentication_window/preload.js 592 KiB [emitted] (name: authentication_window)
  asset upgrade_window/preload.js 592 KiB [emitted] (name: upgrade_window)
  asset welcome_window/preload.js 592 KiB [emitted] (name: welcome_window)
  asset help_window/preload.js 591 KiB [emitted] (name: help_window)
  asset talk_window/preload.js 591 KiB [emitted] (name: talk_window)
  runtime modules 131 KiB 60 modules
  built modules 178 KiB [built]
    modules by path ./node_modules/ 168 KiB
      modules by path ./node_modules/webpack-dev-server/client/ 71.8 KiB 16 modules
      modules by path ./node_modules/webpack/hot/*.js 5.3 KiB 4 modules
      modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
      ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
      ./node_modules/process/browser.js 5.29 KiB [built] [code generated]
    json modules 5.81 KiB
      ./package.json 2.72 KiB [built] [code generated]
      ../../28/server/appsbabies/spreed/package.json 3.09 KiB [built] [code generated]
    ./src/preload.js 3.86 KiB [built] [code generated]
    external "electron" 42 bytes [built] [code generated]
    external "events" 42 bytes [built] [code generated]
  group_0 (webpack 5.89.0) compiled successfully in 1709 ms

group_0:
  assets by chunk 43.7 MiB (id hint: vendors) 11 assets
  assets by info 4.64 MiB [immutable] 9 assets
  assets by path authentication_window/ 17.9 MiB 2 assets
  assets by path help_window/ 15.7 MiB 2 assets
  assets by path upgrade_window/ 15.6 MiB 2 assets
  assets by path welcome_window/ 14 MiB
    asset welcome_window/index.js 14 MiB [emitted] (name: welcome_window)
    asset welcome_window/index.html 4.49 KiB [emitted]
  assets by path talk_window/ 12.5 MiB
    asset talk_window/index.js 12.5 MiB [emitted] (name: talk_window)
    asset talk_window/index.html 1.11 KiB [emitted]
  + 176 assets
  orphan modules 735 KiB [orphan] 172 modules
  runtime modules 163 KiB 91 modules
  modules by path ../../28/server/appsbabies/spreed/ 29.8 MiB (javascript) 203 KiB (asset) 4116 modules
  modules by path ./ 3.86 MiB (javascript) 275 KiB (asset) 514 modules
  modules by mime type image/svg+xml 125 KiB
    data:image/svg+xml;base64,PHN2ZyB4bWxucz0i.. 260 bytes [built] [code generated]
    data:image/svg+xml;base64,PHN2ZyB4bWxucz0i.. 308 bytes [built] [code generated]
    + 207 modules
  modules by path ../../28/server/node_modules/path/ 32.7 KiB
    modules by path ../../28/server/node_modules/path/node_modules/util/ 15.4 KiB 2 modules
    ../../28/server/node_modules/path/path.js 16.7 KiB [built] [code generated]
    ../../28/server/node_modules/path/node_modules/inherits/inherits_browser.js 672 bytes [built] [code generated]
  crypto (ignored) 15 bytes [optional] [built] [code generated]
  data:image/png;base64,iVBORw0KGgoAAAAN.. 261 bytes [built] [code generated]

  ERROR in ../../28/server/appsbabies/spreed/src/App.vue?vue&type=script&lang=js& (./node_modules/esbuild-loader/dist/index.cjs??clonedRuleSet-15!./node_modules/vue-loader/lib/index.js??vue-loader-options!../../28/server/appsbabies/spreed/src/App.vue?vue&type=script&lang=js&) 8:0-77
  Module not found: Error: Package path ./dist/Composables/useIsMobile.js is not exported from package /home/nickv/Nextcloud/28/server/appsbabies/spreed/node_modules/@nextcloud/vue (see exports field in /home/nickv/Nextcloud/28/server/appsbabies/spreed/node_modules/@nextcloud/vue/package.json)
   @ ../../28/server/appsbabies/spreed/src/App.vue?vue&type=script&lang=js& 1:0-253 1:269-272 1:274-524 1:274-524
   @ ../../28/server/appsbabies/spreed/src/App.vue 2:0-55 3:0-50 3:0-50 11:2-8
   @ ../../28/server/appsbabies/spreed/src/main.js 38:0-28 70:19-22
   @ ./src/talk/renderer/talk.main.js 30:6-33

  ERROR in ../../28/server/appsbabies/spreed/src/components/LeftSidebar/LeftSidebar.vue?vue&type=script&lang=js& (./node_modules/esbuild-loader/dist/index.cjs??clonedRuleSet-15!./node_modules/vue-loader/lib/index.js??vue-loader-options!../../28/server/appsbabies/spreed/src/components/LeftSidebar/LeftSidebar.vue?vue&type=script&lang=js&) 24:0-77
  Module not found: Error: Package path ./dist/Composables/useIsMobile.js is not exported from package /home/nickv/Nextcloud/28/server/appsbabies/spreed/node_modules/@nextcloud/vue (see exports field in /home/nickv/Nextcloud/28/server/appsbabies/spreed/node_modules/@nextcloud/vue/package.json)
   @ ../../28/server/appsbabies/spreed/src/components/LeftSidebar/LeftSidebar.vue?vue&type=script&lang=js& 1:0-273 1:289-292 1:294-564 1:294-564
   @ ../../28/server/appsbabies/spreed/src/components/LeftSidebar/LeftSidebar.vue 2:0-63 3:0-58 3:0-58 10:2-8
   @ ./node_modules/esbuild-loader/dist/index.cjs??clonedRuleSet-15!./node_modules/vue-loader/lib/index.js??vue-loader-options!../../28/server/appsbabies/spreed/src/App.vue?vue&type=script&lang=js& 10:0-67 30:4-15
   @ ../../28/server/appsbabies/spreed/src/App.vue?vue&type=script&lang=js& 1:0-253 1:269-272 1:274-524 1:274-524
   @ ../../28/server/appsbabies/spreed/src/App.vue 2:0-55 3:0-50 3:0-50 11:2-8
   @ ../../28/server/appsbabies/spreed/src/main.js 38:0-28 70:19-22
   @ ./src/talk/renderer/talk.main.js 30:6-33

  group_0 (webpack 5.89.0) compiled with 2 errors in 10779 ms
at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/@electron-forge/plugin-webpack/dist/WebpackPlugin.js:220:43
    at Hook.eval [as call] (eval at create (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/Hook.js:14:14)
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/MultiCompiler.js:97:22
    at Hook.eval [as callAsync] (eval at create (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Watching.js:299:28)
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Compiler.js:919:5)
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Watching.js:191:22
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/tapable/lib/Hook.js:18:14)
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/webpack/lib/Compiler.js:882:27
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/neo-async/async.js:2818:7
    at done (/home/nickv/Nextcloud/TalkDesktop/talk-desktop/node_modules/neo-async/async.js:3522:9)
```

## Desktop client

**Talk Desktop client version:** main

**Comment by ShGKme** [comment]
Could you how the result of ?
```
npm ls @nextcloud/vue
```

If it is not `@8.4.0` make sure that fresh dependencies are installed

**Comment by nickvergessen** [comment]
```
$ npm ls @nextcloud/vue
talk-desktop@0.20.0 /home/nickv/Nextcloud/TalkDesktop/talk-desktop
└── @nextcloud/vue@8.4.0
```

I also did `rm -rf node_modules && npm ci && npm run start`

**Comment by ShGKme** [comment]
> I also did `rm -rf node_modules && npm ci && npm run start`

On both `talk-desktop` and `spreed`? I cannot reproduce with `main`

**Comment by nickvergessen** [comment]
```
$ npm ls @nextcloud/vue
talk@19.0.0-dev.0 /home/nickv/Nextcloud/TalkDesktop/spreed
├─┬ @nextcloud/dialogs@5.0.3
│ └── @nextcloud/vue@8.4.0 deduped
├── @nextcloud/vue@8.4.0
└─┬ nextcloud-vue-collections@0.11.1
  └─┬ @nextcloud/vue@7.12.6
    └─┬ @nextcloud/dialogs@4.2.1
      └── @nextcloud/vue@7.12.6 deduped
```

But also redid that one and it doesn't help
