### ISSUE TITLE
Failed to join the conversation. Reload the page.

### ISSUE THREAD

**Issue by Speed7811** [nextcloud/talk-desktop#960]
## Steps to reproduce
1. Open Nextcloud Talk Desktop App
2. Click on a room

### Expected behaviour
On error occur and I can press the "Join call" button.

### Actual behaviour
- Error message "Failed to join the conversation. Reload the page." occur everytime I click on a room.
- "Join call" button is disabled. I cannot press the button although a meeting is running.

## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                              |
| ------------------------------: | ---------------------------------------------------------------------------- |
| **Version**                     | v1.0.0-rc.2                                                                  |
| **Built-in Talk version**       | v20.1.0-rc.2                                                                 |
| **Operating system**            | Windows_NT 10.0.26100 (Windows 11 Pro)                                       |
| **Executable Path**             | C:\Users\XXXXXXXXX\AppData\Local\NextcloudTalk\app-1.0.0-rc2\Nextcloud Talk.exe |
| ****Connected to****            | -                                                                            |
| **Nextcloud server version**    | 28.0.12                                                                      |
| **Nextcloud Talk version**      | 18.0.13                                                                      |
| **`notifications` app enabled** | ✅ yes                                                                        |
| **`notify_push` app enabled**   | ❌ no                                                                         |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": false,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd"
}
```

</details>

<details>
<summary>Client logs</summary>

```
index.js:2 Using locale "" for language "de_DE"
index.js:2 Language pack "de_DE" for "talk_desktop" loaded...
index.js:2 Language pack "de_DE" for "spreed" loaded...
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 [WASM] Loading model of size: 249792
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
printChar @ JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fiwvosbtr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 q
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/state:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 q
l @ index.js:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/state:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 q
n @ index.js:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/znq3okmr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 qcode: "ERR_BAD_REQUEST"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Request failed with status code 405"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}response: {data: '', status: 405, statusText: '', headers: ye, config: {…}, …}stack: "AxiosError: Request failed with status code 405\n    at file:///C:/Users/XXXXXX/AppData/Local/NextcloudTalk/app-1.0.0-rc2/resources/app.asar/.webpack/renderer/talk_window/index.js:2:14692319\n    at XMLHttpRequest.d (file:///C:/Users/XXXXXX/AppData/Local/NextcloudTalk/app-1.0.0-rc2/resources/app.asar/.webpack/renderer/talk_window/index.js:2:14692464)\n    at qe.request (file:///C:/Users/XXXXXX/AppData/Local/NextcloudTalk/app-1.0.0-rc2/resources/app.asar/.webpack/renderer/talk_window/index.js:2:14697979)\n    at async c (file:///C:/Users/XXXXXX/AppData/Local/NextcloudTalk/app-1.0.0-rc2/resources/app.asar/.webpack/renderer/talk_window/index.js:2:1282883)\n    at async d.joinConversation (file:///C:/Users/XXXXXX/AppData/Local/NextcloudTalk/app-1.0.0-rc2/resources/app.asar/.webpack/renderer/talk_window/index.js:2:1345009)"[[Prototype]]: Error
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fznq3okmr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v1/chat/znq3okmr/read:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 Uncaught (in promise) q
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fiwvosbtr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 q
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/state:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 q
l @ index.js:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/state:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 q
n @ index.js:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 
        
        
       PUT https://cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/state 404 (Not Found)
(anonymous) @ index.js:2
xhr @ index.js:2
Se @ index.js:2
Promise.then
_request @ index.js:2
request @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
C @ index.js:2
l @ index.js:1
(anonymous) @ index.js:1
ui @ index.js:2
m @ index.js:2
M.run @ index.js:2
na @ index.js:2
(anonymous) @ index.js:2
Ii @ index.js:2
Promise.then
mi @ index.js:2
Ei @ index.js:2
oa @ index.js:2
M.update @ index.js:2
e.notify @ index.js:2
set @ index.js:2
t @ index.js:1
index.js:1 q {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
l @ index.js:1
await in l
(anonymous) @ index.js:1
ui @ index.js:2
m @ index.js:2
M.run @ index.js:2
na @ index.js:2
(anonymous) @ index.js:2
Ii @ index.js:2
Promise.then
mi @ index.js:2
Ei @ index.js:2
oa @ index.js:2
M.update @ index.js:2
e.notify @ index.js:2
set @ index.js:2
t @ index.js:1

```

</details>

**Comment by Speed7811** [comment]
With 1.0 the same

## Diagnosis and logs

<details>
<summary>Diagnosis report</summary>

### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                          |
| ------------------------------: | ------------------------------------------------------------------------ |
| **Version**                     | v1.0.0                                                                   |
| **Built-in Talk version**       | v20.1.0                                                                  |
| **Operating system**            | Windows_NT 10.0.26100 (Windows 11 Pro)                                   |
| **Executable Path**             | C:\Users\XXXXXX\AppData\Local\NextcloudTalk\app-1.0.0\Nextcloud Talk.exe |
| ****Connected to****            | -                                                                        |
| **Nextcloud server version**    | 28.0.12                                                                  |
| **Nextcloud Talk version**      | 18.0.13                                                                  |
| **`notifications` app enabled** | ✅ yes                                                                    |
| **`notify_push` app enabled**   | ❌ no                                                                     |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": false,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd",
  "enableCallbox": "respect-dnd"
}
```

</details>

<details>
<summary>Client logs</summary>

index.js:2 Using locale "" for language "de_DE"
index.js:2 Language pack "de_DE" for "talk_desktop" loaded...
index.js:2 Language pack "de_DE" for "spreed" loaded...
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 [WASM] Loading model of size: 249792
JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
printChar @ JitsiStreamBackgroundEffect.worker.js?v=fa1b69e42302a02d7a71:1
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
cloud.XXXXXX.de:8443/ocs/v2.php/apps/user_status/api/v1/statuses/_1F94540B-9A3A-47BC-916A-4FA9ADB5D188:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fznq3okmr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/znq3okmr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 q
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fiwvosbtr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/iwvosbtr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 q
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/znq3okmr/participants/active:1 
        
        
       Failed to load resource: the server responded with a status of 405 ()
index.js:2 q
joinConversation @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/dav/api/v1/events/upcoming?location=https:%2F%2Fcloud.XXXXXX.de%2Findex.php%2Fcall%2Fznq3okmr:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:2 q
getUpcomingEvents @ index.js:2
cloud.XXXXXX.de:8443/ocs/v2.php/apps/spreed/api/v4/room/znq3okmr/participants/state:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
index.js:1 q
l @ index.js:1


</details>

**Comment by dennisTGC** [comment]
> Could you try to log out and login again to check if it solves the issue?

yes that resolved the issue. 

Can you tell me where the logfiles are created? 

and for reference (I use flatpak):
```
### Diagnosis report

| **Nextcloud Talk Desktop**      |                                                                                      |
| ------------------------------: | ------------------------------------------------------------------------------------ |
| **Version**                     | v1.0.1                                                                               |
| **Built-in Talk version**       | v20.1.1                                                                              |
| **Operating system**            | Linux 6.8.0-51-generic (#52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024) |
| **Executable Path**             | /app/lib/com.nextcloud.talk/Nextcloud Talk                                           |
| **Using Wayland**               | ✅ yes                                                                                |
| ****Connected to****            | -                                                                                    |
| **Nextcloud server version**    | 28.0.10                                                                              |
| **Nextcloud Talk version**      | 18.0.12                                                                              |
| **`notifications` app enabled** | ✅ yes                                                                                |
| **`notify_push` app enabled**   | ❌ no                                                                                 |

#### Application config

```json
{
  "theme": "default",
  "systemTitleBar": true,
  "monochromeTrayIcon": false,
  "zoomFactor": 1,
  "playSoundChat": "respect-dnd",
  "playSoundCall": "respect-dnd",
  "enableCallbox": "respect-dnd"
}
```

**Comment by Speed7811** [comment]
I tried to logout and login but the problem still exists after the login.

**Comment by Speed7811** [comment]
Hey,

we are using local rooms and I see an index.php name in the browser. So I think that mod_rewrite is enabled but if necessary I will check tomorrow morning the server. At the moment we are using NC29

I have an identical setup with NC30 but on a default port. With this server there is no problem. 

Best regards

Rainer

**Comment by Speed7811** [comment]
I just checked it - mod_rewrite is enabled.

**Comment by dennisTGC** [comment]
I did not experience this issue anymore after the logout and login. As you can't reproduce, it might have to do with some left over authentication artifacts? 

Anyway, if I experience the issue again I'll let you know. I can also do troubleshooting to see if I can reproducte the issue. Running on default port and optional TURN server in front of it (although I experienced this from home, which does not use the TURN server).

**Comment by Speed7811** [comment]
@ShGKme 

> * You still have this error after logging out and login again (you can successfully log in)
Yes, I tried it several times and the error still occurs

>   * Also, what Nextcloud server version are you on? Have you upgraded to 29?
Yes, I upgraded to 29 

> * You can see the list of the rooms, but you cannot join any room
Yes, I can see the rooms but when I click on the room the error occur.

>   * Are you able to create a room?
I didn't try it.

> * You don't have any errors in the web-browser and mobile clients
In the web-browser there is no problem. I didn't test it with a mobile client.

Best regards 

Rainer

**Comment by Speed7811** [comment]
In the meantime, we have upgraded to NC30, and with this version the problem doesn't exists. In my opionion you can close this issue.

**Comment by remcoboerma** [comment]
Had the same issue after installing v1.1.9 over a previous version (flatpak);logged in to the server, it failed.  tried several restarts: no succes. logout, login: it works.

**Comment by ShGKme** [comment]
> logout, login: it works.

Likely something required capabilities reload. Fixed in a beta version
